apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-creds
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-creds   # AWS Secret Name
        property: admin-user       # JSON property
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-creds
        property: admin-password

