apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./ingress.yaml
  - ./external-secret.yaml
  - ./rbac.yaml
  - ../../base/homepage
patches:
  - path: deployment-patch.yaml
