apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./flux-system
  - ./namespace-dev.yaml
  - ./namespace-staging.yaml
  - ./apps-dev.yaml
  - ./apps-staging.yaml
  - ./infrastructure.yaml
