apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./cilium
  - ./cloudflare-tunnel
  - ./external-secrets
  - ./kube-prometheus-stack
  - ./longhorn
  - ./metallb
  - ./renovate
  - ./traefik
  - ./ci-access

