apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding25
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: linkding25
  template:
    metadata:
      labels:
        app: linkding25
    spec:
      containers:
        - name: linkding25
          image: sissbruecker/linkding:1.41.0-plus-alpine
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/linkding/data
              name: linkding-volume
          envFrom:
            - secretRef:
                name: test25
      volumes:
        - name: linkding-volume
          persistentVolumeClaim:
            claimName: linkding-volume
